---
title: "EC: Coding With Python Assignment"
author: "Jin Chang"
date: "2/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r part3, echo=TRUE, warning=FALSE}
# Task 10
random <- sample(0:100, 1)
if(random <= 25) {
  print("1st Quartile")
} else if(random > 25 && random <= 50) {
  print("2nd Quartile")
} else if(random > 50 && random <= 75) {
  print("3rd Quartile")
} else {
  print("4th Quartile")
}
```

```{r part4, echo=TRUE, warning=FALSE}
# Task 11
cities = list("Seattle", "Los Angeles", "New York", "Nashville", "Oceanshore", "Tacoma")

for (city in cities) {
  string <- paste("Warning, residents of ", city, ", temperatures will reach sub-zero temperatures today, please stay indoors if possible\n")
  print(string)  
}

# Task 12 
temp <- list()
states <- list("Washington", "California", "Nevada", "Idaho", "Montana", "Utah", "Colorado", "New Mexico")

for (state in states) {
    filename <- "U://Users/Zhang/Geog_458/filename.shp"
    filename = gsub("filename", state, filename)
    temp[[state]] <- filename
    print(temp[[state]])
}

# Task 13
count <- 10
while (count >= 0) {
  countdwn <- paste("T-minus", count, sep=" ")
  print(countdwn) 
  count <- count - 1
}
```

```{r part5, echo=TRUE, warning=FALSE}
# Task 14
countdown <- function(count) {
  while (count >= 0) {
  countdown <- paste("T-minus", count, sep=" ")
  print(countdown) 
  count <- count - 1
  }
}

countdown(10)

# Task 15
quartile_calc <- function(num) {
  if (num < 0 || num > 100) {
    return("Error: number is out of bounds")
  }
  
  if (num <= 25) {
      print("1st Quartile")
  } else if (num <= 50 && num > 25) {
      print("2nd Quartile") 
  } else if (num <= 75 && num > 50) {
      print("3rd Quartile")
  } else {
      print("4th Quartile")
  }
}

# Test
quartile_calc(29)
quartile_calc(-2)
quartile_calc(101)
```
